# Generated by Django 4.2.27 on 2026-03-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_seed_initial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
